### ISSUE TITLE
the inline if-expression on line 1 evaluated to false and no else section was defined.

### ISSUE THREAD

**Issue by marcin-github** [GROG/ansible-role-package#10]
Hello!
I'm getting something like this:

```

TASK [grog.package : Apt] ************************************************************************************************************************************************************************************
fatal: [XXXX]: FAILED! => {"msg": "the inline if-expression on line 1 evaluated to false and no else section was defined."}
```
ansible 2.9.6

I don't know why it happened only on one host and I don't know where is miisign "else".

**Comment by groggemans** [comment]
Hi Marcin

Is this a repeatable issue?

Can you post the output when you run this with `-vvv` ? that might show us whats going on.
It would also be useful to share your input.

Thank you
Gertjan

**Comment by marcin-github** [comment]
Hi,
on given host it's repeteable issue.
Here is how I run playbook:
`
 ansible-playbook -i inventories/ -D main.yml  -vvv -C -t base_package
`
snip from main.ynl
`
    - { role: grog.package, when: inventory_hostname_short == ansible_hostname , tags: base_package }
`

```
[...]
TASK [grog.package : Apt] ************************************************************************************************************************************************************************************
task path: /home/xxx/ansible/roles/grog.package/tasks/package-apt.yml:3
fatal: [decprxm1.yyyyy]: FAILED! => {
    "msg": "the inline if-expression on line 1 evaluated to false and no else section was defined."
}
Callback Exception:
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 324, in send_callback
    method(*new_args, **kwargs)
   File "/usr/lib/python2.7/dist-packages/ansible/plugins/callback/mail.py", line 223, in v2_runner_on_failed
    self.mail_result(result, 'Failed')
   File "/usr/lib/python2.7/dist-packages/ansible/plugins/callback/mail.py", line 213, in mail_result
    self.mail(subject=subject, body=body)
   File "/usr/lib/python2.7/dist-packages/ansible/plugins/callback/mail.py", line 108, in mail
    smtp = smtplib.SMTP(self.smtphost, port=self.smtpport)
   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
   File "/usr/lib/python2.7/smtplib.py", line 292, in _get_socket
    return socket.create_connection((host, port), timeout)
   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt.py
[...]
```

**Comment by groggemans** [comment]
That's a peculiar output.. from what I can tell from that trace-back you are using the mail callback to send an email on failure, is that correct? It looks like it's actually trowing an error because it can't send out that email. That might be causing the unexpected error message.

Can you try to run this without the mail callback? It might produce a different error message with the actual issue at hand.

I assume that this host is running a Debian based operating system? I suspect that the `python-apt` package might be missing on these hosts..

**Comment by marcin-github** [comment]
I turned off callback. python-apt is installed. This os is Debian.
Finally I found reason of such behaviour.
In package_list I've got:
```
  - name: qemu-guest-agent
    state: "{{ 'present' if ansible_facts['virtualization_role'] == 'guest' and ansible_facts['virtualization_type'] == 'kvm' }}"
```
but this host has `virtualization_role == 'host'`
so it looks like error from if statement above was passed down to task `grog.package: Apt`. Uff:)
Thank you for your attention, problem was on my side.

**Comment by groggemans** [comment]
I'm happy we got this figured out :slightly_smiling_face:
