### ISSUE TITLE
Difference from Ansible's package manager

### ISSUE THREAD

**Issue by stelgenhof** [GROG/ansible-role-package#13]
Thanks for this nice Ansible role. I was wondering how this Ansible role differs from Ansible's standard OS package manager? (See: https://docs.ansible.com/ansible/2.3/package_module.html).

**Comment by groggemans** [comment]
Hi @stelgenhof 

The main reason this role was created was to easily install packages that have different names on different linux distributions.
To quote the package module documentation;

> Be aware that packages are not always named the same and this module will not 'translate' them per distro.

This role will allow you to provide different names for different package managers.

**Comment by stelgenhof** [comment]
@groggemans Thanks for the explanation!
