### ISSUE TITLE
package_lists merge?

### ISSUE THREAD

**Issue by mikerj1** [GROG/ansible-role-package#8]
Hi Grog, thanks again for you work.  I've got a group_vars/all.yml that has a list of packages, then host_vars/host1.yml.  It looks like if package_list is defined in host1.yml, only the packages in package_list from host_vars/host1.yml get used.  I thought these would be merged, but doesn't seem to be the case.  Is this user error, or in fact the case?  Thanks

**Comment by groggemans** [comment]
Thank you for using the role!

They should be merged, are you using `package_list_host` variable in the `host_vars/host.yml` file?
Can you post a minimal version of your config? (just the `package_xxx` vars and file names/locations)
Have you altered the ansible.cfg file?

**Comment by mikerj1** [comment]
Just using package_list

I have this in group_vars/all.yml

package_list:
  - name: epel-release
  - name: telnet
  - name: yum-plugin-versionlock
  - name: git
  - name: bzip2
  - name: nrpe
  - name: nagios-common
  - name: nagios-plugins
  - name: nagios-plugins-perl
  - name: nagios-plugins-load
  - name: nagios-plugins-mailq
  - name: nagios-plugins-swap
  - name: nagios-plugins-disk
  - name: nagios-plugins-ntp

Then in host_vars/logmon.yml

package_list:
  - name: nagios
  - name: logcheck

I just tried another test.  In group_vars/all.yml, I added wget to the list of packages to install, which isn't present on any system yet.  Output:

TASK [GROG.package : Yum] ******************************************************
ok: [app01] => (item={u'name': u'epel-release'})
ok: [vpn] => (item={u'name': u'epel-release'})
ok: [agg01] => (item={u'name': u'epel-release'})
ok: [logmon] => (item={u'name': u'epel-release'})
ok: [app01] => (item={u'name': u'telnet'})
ok: [agg01] => (item={u'name': u'telnet'})
ok: [vpn] => (item={u'name': u'telnet'})
ok: [logmon] => (item={u'name': u'nagios'})
ok: [app01] => (item={u'name': u'yum-plugin-versionlock'})
ok: [agg01] => (item={u'name': u'yum-plugin-versionlock'})
ok: [vpn] => (item={u'name': u'yum-plugin-versionlock'})
ok: [app01] => (item={u'name': u'git'})
ok: [logmon] => (item={u'name': u'logcheck'})
ok: [app01] => (item={u'name': u'nrpe'})
ok: [vpn] => (item={u'name': u'git'})
ok: [agg01] => (item={u'name': u'git'})
ok: [agg01] => (item={u'name': u'nrpe'})
ok: [vpn] => (item={u'name': u'bzip2'})
ok: [vpn] => (item={u'name': u'nrpe'})
ok: [vpn] => (item={u'name': u'nagios-common'})
ok: [vpn] => (item={u'name': u'nagios-plugins'})
ok: [vpn] => (item={u'name': u'nagios-plugins-perl'})
ok: [vpn] => (item={u'name': u'nagios-plugins-load'})
ok: [vpn] => (item={u'name': u'nagios-plugins-mailq'})
ok: [vpn] => (item={u'name': u'nagios-plugins-swap'})
ok: [vpn] => (item={u'name': u'nagios-plugins-disk'})
ok: [vpn] => (item={u'name': u'nagios-plugins-ntp'})
changed: [vpn] => (item={u'name': u'wget'})


I only have a host_vars file for a single host right now, however I do have another group_vars file called not-vpn.yml, which as the name implies, includes all hosts except vpn.  Its contents:

package_list:
  - name: epel-release
  - name: telnet
  - name: yum-plugin-versionlock
  - name: git
  - name: nrpe

So it in this case, only the vpn server got wget.

**Comment by groggemans** [comment]
Ok, this behavior is as expected.

The idea is, that you specify packages for all hosts in the `package_list` variable. This should go in the `group_vars/all.yml` file. You can then specify group specific packages eg. `wget` for vpn servers, in the `group_vars/vpn.yml` file with the `package_list_group` variable.

If a host needs some specific packages, this can be done by adding them to the `package_list_host` variable, which should go in `host_vars/hostname.yml`.

All these variables (`package_list{_group, _host}`) are then merged when installing the packages.

Note that this won't work with hosts that are in multiple groups!, the last `package_list_group` variable will be used, unless you alter your `ansible.cfg` file (`hash_behaviour = merge`)

The role was designed this way so you can specify host and group specific packages without having to use the merge behavior (which makes it impossible to fully overwrite hashes).

What if you need groep specific packages when using multiple groups for the same host? Use roles! make a role for each group and add the `GROG.package` role as a dependency. Now you can just pass your packages to the `GROG.package` role without interfering with packages for other groups. Let me know if you need more information about how to do that.

**Comment by groggemans** [comment]
@mikerj1 I'm closing this issue, please let me know if you have any further questions!

**Comment by mikerj1** [comment]
Sorry for the delay getting back to you.  Thanks for the explanation!
