### ISSUE TITLE
handling duplicated package 

### ISSUE THREAD

**Issue by taktus** [GROG/ansible-role-package#9]
Hello Gertjan,
Having 3 lists of packages is good idea but test please what happens if the package is on more than one list. The role tries to install it twice or three times. It would be good to eliminate duplicates to speed up installation a bit. 
Why would you modify the loop slightly  changing

  with_flattened:
     - "{{ package_list }}"
     - "{{ package_list_host }}"
     - "{{ package_list_group }}"

with singe line of code like:

  with_items: "{{ (package_list + package_list_group +  package_list_host ) | list | unique  }}"

cheers
Marek Krasnowski

**Comment by groggemans** [comment]
Hi Marek

Thank you for the suggestion!
I think this would indeed be a nice improvement.

Let me know if you want to create a PR yourself, otherwise I'll implement this when I find some time.

Kind regards
Gertjan

**Comment by lidopaglia** [comment]
Hello @groggemans and @taktus, hoping my change is helpful.

**Comment by groggemans** [comment]
This issue was fixed by @lidopaglia's PR.

Thank you both!
